copyright: Copyright (c) Ultraviolet
repo_url: https://github.com/ultravioletrs/prism
site_description: Prism Platform
site_name: Prism Docs
site_url: https://docs.prism.ultraviolet.rs
edit_uri: ""
theme:
  name: material
  logo: img/Prism_logo.png
  favicon: img/Prism_logo.png
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"

nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Getting Started: getting-started.md
  - Billing: billing.md
  - Computations: computations.md
  - Computation Policies: policies.md
  - Users: users.md
  - Projects: projects.md
  - UI: ui.md
  - Certs: certs.md
  - Backends: backends.md
