copyright: Copyright (c) Ultraviolet
repo_url: https://github.com/ultravioletrs/prism
site_description: Prism Platform
site_name: Prism Docs
site_url: https://docs.prism.ultraviolet.rs
edit_uri: ""
theme:
  name: material
  logo: img/Prism_logo.png
  favicon: img/Prism_logo.png
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"

nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Getting Started: getting-started.md
  - Access Control: access-control.md
  - Computations: computations.md
  - Computation Roles: roles.md
  - Assets: assets.md
  - Computation Logs: computation-logs.md
  - Users: users.md
  - Workspaces: workspaces.md
  - Certs: certs.md
  - Algorithms: algorithms.md
  - Dashboard: dashboard.md
  - CVMs: cvms.md
